medline/consulta/urls.py
from django.urls import path
from consulta import views as v


urlpatterns =[
    path('', v.home, name="home"),
    path('login', v.login_request, name='login_request'),
    path('logout/', v.logout_request, name='logout_request'),
    path('cadastro/paciente', v.register_patient, name="register_patient"),
    path('cadastro/medico', v.register_doctor, name="register_doctor"),
    path('perfil/medico', v.perfil_medico, name="perfil_medico"),
    path('consultas_medicas/', v.consultas_medicas, name="consultas_medicas"),
    path('consultas_medicas/excluir_horario/<int:id>', v.excluir_horario, name="excluir_horario"),
    path('consultas/', v.consultas, name="consultas"),
    path('consultas/detalhes_consulta/<int:id>', v.detalhes_consulta, name="detalhes_consulta"),
    path('especialidades/', v.especialidades, name="especialidades"),
    path('cidades/', v.cidades, name="cidades"),
    path('pedidos/', v.pedidos, name="pedidos"),
    path('pedidos/detalhes_pedido/<int:id>', v.detalhes_pedido, name="detalhes_pedido"),
    path('carrinho/', v.carrinho, name="carrinho"),
    path('checagem/', v.checagem, name ="checagem"),
    path('update_item/', v.updateItem, name="update_item"),
    path('process_order/', v.processOrder, name="process_order"),
]

medline/medline/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('consulta.urls')),
]
# fornece os arquivos estáticos durante o desenvolvimento
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medline/consulta/models.py
from django.db import models
from consulta.models_login import User

# Create your models here.

class Pacientes(User):
    role = models.CharField(max_length=9, default='paciente')
    birth = models.DateField(verbose_name='Data de Nascimento') # formato: 1991-11-15
    cpf = models.CharField(max_length=11, null=True, verbose_name='CPF')

    def __str__(self):
        return self.get_full_name()

    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'


class Medicos(User):
    role = models.CharField(max_length=9, default='medico')
    birth = models.DateField(verbose_name='Data de Nascimento') # formato: 1991-11-15
    cpf = models.CharField(max_length=11, null=True, verbose_name='CPF')
    crm = models.CharField(max_length=20, null=True)
    foto = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.get_full_name()

    @property
    def imageURL(self):
        try:
            url = self.foto.url
        except:
            url = ''
        return url

    class Meta:
        verbose_name = 'Médico'
        verbose_name_plural = 'Médicos'


class Especialidades(models.Model):
    tipos = [('225105 - Acupuntura','Médico Acumputurista'),
             ('225110 - Alergia e Imunologia','Médico Alergista e Imunologista'),
             ('225151 - Anestesiologia','Médico anestesiologista'),
             ('225115 - Angiologia','Médico angiologista'),
             ('225120 - Cardiologia','Médico Cardiologista'),
             ('225124A - Cardiologia Pediátrica','Médico Cardiologista'),
             ('225210 - Cirurgia Cardiovascular','Médico Cirurgião Cardiovascular'),
             ('225215 - Cirurgia de Cabeça e Pescoço','Médico cirurgião de cabeça e pescoço'),
             ('225295 - Cirurgia de Mão','Médico cirurgião da mão'),
             ('225225 - Cirurgia Geral ','Médico cirurgião geral '),
             ('225230 - Cirurgia Pediátrica','Médico cirurgião pediátrico'),
             ('225235 - Cirurgia Plástica','Médico cirurgião plástico '),
             ('225305 - Citopatologia','Médico citopatologista'),
             ('225125 - Clínica Médica','Médico clínico'),
             ('225280 - Coloproctologia','Médico proctologista'),
             ('225135 - Dermatologia','Médico dermatologista'),
             ('225155 - Endocrinologia e Metabologia','Médico endocrinologista e metabologista'),
             
             ('225310A - Endoscopia digestiva','Médico em endoscopia'),
             ('225310B - Endoscopia respiratoria','Médico em endoscopia'),
             ('225160 - Fisiatria','Médico fisiatra'),
             ('223605 - Fisioterapia','Fisioterapeuta geral'),
             ('223810 - Fonoaudiologia','Fonoaudiólogo'),
             ('225165 - Gastroenterologia','Médico gastroenterologista'),
             ('225175 - Genetica Medica','Médico geneticista'),
             ('225180 - Geriatria','Médico geriatra'),
             ('225250 - Ginecologia e obstetricia','Médico ginecologista e obstetra'),
             ('225185 - Hematologia e hemoterapia','Médico Hematologista'),
             ('225210A - Hemodinamica e Cardiologia Intervencionista','Hemodinamica e Cardiologia Intervencionista'),
             ('225165A - Hepatologia','Hepatologia'),
             ('225195 - Homeopatia','Médico Homeopata'),
             ('225103 - Infectologia','Médico infectologista'),
             ('225255 - Mastologia','Médico Mastologista'),
             ('225315 - Medicina nuclear','Médico em medicina nuclear'),
             ('225170 - Medico Clinico Geral','Médico Generalista'),
             ('225109 - Nefrologia','Médico Nefrologista'),
             ('225124H - Neonatologia','Neonatologia'),
             ('225124I - Neurologia pediatrica','Médico neurologista'),
             ('225260 - Neurocirurgia ','Médico neurocirurgião'),
             ('225112 - Neurologia','Médico neurologista'),

             ('225118 - Nutrologia','Médico nutrologista'),
             ('225265 - Oftalmologia','Médico oftalmologista'),
             ('225121 - Oncologia','Médico oncologista clínico'),
             ('225270 - Ortopedia e traumatologia','Médico ortopedista e traumatologista'),
             ('225275 - Otorrinolaringologia','Médico otorrinolaringologista'),
             ('225335 - Patologia clínica/Medicina laboratorial','Médico patologista clínico /medicina laboratorial'),
             ('225124 - Pediatria','Médico pediatra'),
             ('225127 - Pneumologia','Médico pneumologista'),
             ('251510 - Psicologia','Psicólogo clínico'),
             ('225133 - Psiquiatria','Médico psiquiatra'),
             ('225320 - Radiologia e diagnóstico por imagem','Médico em radiologia e diagnóstico por imagem'),
             ('225330 - Radioterapia','Médico radioterapeuta'),
             ('225136 - Reumatologia','Médico reumatologista'),
             ('223905 - Terapia ocupacional','Terapeuta ocupacional'),
             ('225285 - Urologia','Médico Médico urologista'),
             ('223268 - Cirurgia e traumatologia buco-maxilo-facial','Cirurgião dentista - traumatologista bucomaxilofacial'),
             ('223208 - Dentista clinico geral','Cirurgião dentista - clínico geral'),
             ('223212 - Endodontia','Cirurgião dentista - endodontista'),
             ('223220 - Estomatologia','Cirurgião dentista - estomatologista'),
             ('223224 - Implantodontia','Cirurgião dentista - implantodontista'),
             ('223236 - Odontopediatria','Cirurgião dentista - odontopediatra'),
             ('223240 - Ortodontia','Cirurgião dentista - ortopedista e ortodontista'),

             ('223248 - Periodontia','Cirurgião dentista - periodontista'),
             ('223256 - Protese dentaria','Cirurgião dentista - protesista'),
             ('223260 - Imaginologia odontologica','Imaginologia odontologica'),
             ('225220 - Cirurgia do aparelho digestivo','Médico cirurgião do aparelho digestivo'),
             ('225240 - Cirurgia toracica','Médico cirurgião torácico'),
             ('225124B - Endocrinologia pediatrica','Médico endocrinologista e metabologista'),
             ('223845 - Foniatria','Fonoaudiólogo'),
             ('225124C - Gastroenterologia pediatrica','Médico gastroenterologista'),
             ('225124D - Hematologia e hemoterapia pediatrica','Médico Hematologista'),
             ('225124E - Medicina do adolescente','Medicina do adolescente'),
             ('225150 - Medicina intensiva','Médico em medicina intensiva'),
             ('225124F - Medicina intensiva pediatrica','Médico em medicina intensiva'),
             ('225124G - Nefrologia pediatrica','Médico Nefrologista'),
             ('223710 - Nutricionista','Nutricionista'),
             ('225290 - Oncologia cirurgica','Médico oncologista clínico'),
             ('225122 - Oncologia pediatrica','Médico oncologista clínico'),
             ('225124K - Pneumologia pediatrica','Médico pneumologista'),
             ('225133A - Psiquiatria da infancia eda adolescencia','Psicopedagogo'),
             ('225124L - Reumatologia pediatrica','Médico reumatologista'),
             ('223280 - Dentistica','Dentistica'),
             ('223284 - Disfuncao temporomandibular e dor orafacial.','Cirurgião dentista - disfunção temporomandibular e dor orofacial'),
             ('223228 - Odontogeriatria','Cirurgião dentista - odontogeriatra'),
             
             ('223288 - Odontologia para pacientes com necessidades especiais','Cirurgião dentista - odontologia para pacientes com necessidades especiais'),
             ('223284A - Ortopedia funcional dos maxilares','Ortopedia funcional dos maxilares'),
             ('999999 - Medicamentos Hospitalares','Medicamentos Hospitalares'),
             ('999999A - Opme','Opme'),
             ('225151A - Dor','Dor'),
             ('225112A - Medicina do Sono','Medicina do Sono'),
             ('225203 - Cirurgia Vascular','Médico em cirurgia vascular'),
             ('225310 - Endoscopia','Médico em endoscopia'),
             ('225160A - Medicina Fisica e Reabilitação','Medicina Fisica e Reabilitação'),
             ('225325 - patologia','Médico patologista'),
             ('251605 - Assistente social ','Assistente social '),
             ('223505 - Enfermagem','Técnico de enfermagem'),
             ('999999B - Não Informado','CBO desconhecido ou não informado pelo solicitante'),

            ]
    especialidade = models.CharField(max_length=100, choices=tipos)
    

    def __str__(self):
        return self.especialidade
    
    class Meta:
        verbose_name = 'Especialidade'
        verbose_name_plural = 'Especialidades'
    

class Medicos_especialidade(models.Model):
    id_medico = models.ForeignKey(Medicos, on_delete=models.SET_NULL, null=True)
    id_especialidade = models.ForeignKey(Especialidades, on_delete=models.SET_NULL, null=True)
    preco = models.DecimalField(max_digits=7, decimal_places=2)
    certificado_especialidade = models.ImageField(null=True, blank=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Médico Por Especialidade'
        verbose_name_plural = 'Médicos Por Especialidade'

class Localidades(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    cep = models.CharField(max_length=11, null=True)
    rua = models.CharField(max_length=50, null=True)
    bairro = models.CharField(max_length=50, null=True)
    cidade = models.CharField(max_length=100, null=True)
    estado = models.CharField(max_length=2, null=True)
    complemento = models.CharField(max_length=30, null=True)


    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Localidade'
        verbose_name_plural = 'Localidades'

class Agendas(models.Model):

medline/consulta/forms/form_login.py
from django import forms
from consulta.models_login import User


class UserLogin(forms.ModelForm):

    class Meta:
        model = User
        fields = [
            'username',
            'password'
        ]
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'class': 'inputs', 'placeholder': 'Usuário...'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'class': 'inputs', 'placeholder': 'Senha...'}),
        }

medline/consulta/forms/form_registration.py
# -*- coding:utf-8 -*-

from django import forms
from django.contrib.auth.hashers import make_password

from consulta.models_login import User
# from consulta.models import Pacientes, Medicos
from consulta.models import *


class patientRegistration(forms.ModelForm):

    class Meta:
        model = Pacientes
        fields = [
            'username',
            'password',
            'first_name',
            'last_name',
            'email',
            'birth',
            'cpf',
        ]

        widgets = {
            'username': forms.TextInput(attrs={'class': 'inputs', 'placeholder': 'Insira seu nome de usuário'}),
            'password': forms.PasswordInput(attrs={'class': 'inputs', 'placeholder': 'Insira sua senha'}),
            'first_name': forms.TextInput(attrs={'class': 'inputs', 'placeholder': 'Insira seu primeiro nome'}),
            'last_name': forms.TextInput(attrs={'class': 'inputs', 'placeholder': 'Insira seu sobrenome'}),
            'email': forms.TextInput(attrs={'class': 'inputs', 'type': 'email', 'placeholder': 'Insira seu email'}),
            'birth': forms.TextInput(attrs={'class': 'inputs', 'type': 'date', 'title': 'Data de Nascimento'}),
            'cpf': forms.TextInput(attrs={'class': 'inputs', 'placeholder': 'CPF'}),
        }


    # Encrypt password before saving it to User Model
    def save_user(self, commit=True):
        user = super(patientRegistration, self).save(commit=False)
        user.password = make_password(user.password)
        if commit:
            user.save()

        return user        


class doctorRegistration(forms.ModelForm):

    class Meta:
        model = Medicos
        fields = '__all__'
        exclude = ['user_permissions','groups', 'last_login','is_staff', 'is_active', 'is_admin',
                   'is_superuser', 'date_joined','role']

        widgets = {
            'username': forms.TextInput(attrs={'class': 'inputs', 'placeholder': 'Insira seu nome de usuário'}),
            'password': forms.PasswordInput(attrs={'class': 'inputs', 'placeholder': 'Insira sua senha'}),
            'first_name': forms.TextInput(attrs={'class': 'inputs', 'placeholder': 'Insira seu primeiro nome'}),
            'last_name': forms.TextInput(attrs={'class': 'inputs', 'placeholder': 'Insira seu sobrenome'}),
            'email': forms.TextInput(attrs={'class': 'inputs', 'type': 'email', 'placeholder': 'Insira seu email'}),
            'birth': forms.TextInput(attrs={'class': 'inputs', 'type': 'date', 'title': 'Data de Nascimento'}),
            'cpf': forms.TextInput(attrs={'class': 'inputs', 'placeholder': 'CPF'}),
            'crm': forms.TextInput(attrs={'class': 'inputs', 'placeholder': 'CRM'}),
            'foto': forms.FileInput(attrs={'class': 'inputs'}),
        }


    # Encrypt password before saving it to User Model
    def save_user(self, commit=True):
        user = super(doctorRegistration, self).save(commit=False)
        user.password = make_password(user.password)
        if commit:
            user.save()

        return user

class medicosEspecialidades(forms.ModelForm):

    class Meta:
        model = Medicos_especialidade
        fields = '__all__'
        

        widgets = {
            'id_especialidade': forms.Select(attrs={'class': 'inputs', 'class': 'custom-select'}),
            'preco': forms.TextInput(attrs={'class': 'inputs','class': 'form-control'}),
            'certificado_especialidade': forms.FileInput(attrs={'class': 'inputs','class': 'custom-file-input', 'id':"inputGroupFile01" }),
        }

class agendasForm(forms.ModelForm):

    class Meta:
        model = Agendas
        fields = '__all__'
        

        widgets = {
            'id_medico': forms.Select(attrs={'class':'custom-select'}),
            'id_especialidade': forms.Select(attrs={'class':'form-control'}),
            'tipos_consulta': forms.Select(attrs={'class':'form-control'}),
            'data': forms.TextInput(attrs={'class':'form-control', 'type': 'date'}),
            'hora': forms.TextInput(attrs={'class':'form-control', 'type': 'time'}),
        }

class localidades(forms.ModelForm):

    class Meta:
        model = Localidades
        fields = '__all__'
        

        widgets = {
            'cep': forms.TextInput(attrs={'class': 'form-control'}),
            'rua': forms.TextInput(attrs={'class': 'form-control'}),
            'bairro': forms.TextInput(attrs={'class': 'form-control'}),
            'cidade': forms.TextInput(attrs={'class': 'form-control'}),
            'estado': forms.TextInput(attrs={'class': 'form-control'}),
            'complemento': forms.TextInput(attrs={'class': 'form-control'}),
        }

medline/consulta/templates/checagem.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Checagem{% endblock %}</title>
{% block links %} 
<link rel="stylesheet" type="text/css" href="{% static 'css/carrinho.css' %}">
{% endblock %}
{% block main %}
<div class="row col-md-12">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form id="form">
                <div id="user-info">
                    <hr>
                    <p>Nome e email:</p>
                    <hr>
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Nome Completo.." value="{{request.user.pacientes.first_name}} {{request.user.pacientes.last_name}}">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="email" name="email" placeholder="Email.." value="{{request.user.pacientes.email}}">
                    </div>
                </div>

                <div id="shipping-info">
                    <hr>
                    <p>Informações de endereço:</p>
                    <hr>
                    <div class="form-field">
                        <input required class="form-control" type="text" id='id_cep' name="cep" placeholder="Cep.." onblur="pesquisacep(this.value);">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="text" id='id_rua' name="rua" placeholder="Rua..">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="text" id='id_bairro' name="bairro" placeholder="Bairro..">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="text" id='id_cidade' name="cidade" placeholder="Cidade..">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="text" id='id_estado' name="estado" placeholder="Estado..">
                    </div>
                    
                </div>

                <hr>
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
            </form>
        </div>
        <br>

        <div hidden class="box-element" id="payment-info">
            <small>Formas de pagamento PayPal:</small>
            <div id="paypal-button-container"></div>
            <button class="btn btn-primary" id="make-payment">Confirmar Pagamento</button>
        </div>

    </div>

    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'carrinho' %}">&#x2190;Back to Cart</a>
            <hr>
            <h3>Resumo do Pedido</h3>
            <hr>
            {% for item in items %}
            <div class="cart-row">
                <div class="itens_consulta" style="flex:2"><img class="row-image" src="{{ item.id_medicos_especialidade.id_medico.imageURL}}"> {{ item.id_medicos_especialidade.id_medico}}</div>
                <div class="itens_consulta">{{ item.id_medicos_especialidade.id_especialidade}}</div>
                <div class="itens_consulta">R${{ item.id_medicos_especialidade.preco|floatformat:2 }}</div>
                
            </div>
            {% endfor %}

            <h5>Itens: {{ compras.get_cart_items }}</h5>
            <h5>Total: R${{ compras.get_cart_total|floatformat:2 }}</h5>
        </div>
    </div>
</div>
{% endblock main %}
{% block scripts %}
<script type="text/javascript" src="{% static 'js/cep.js' %}"></script>
<script
    src="https://www.paypal.com/sdk/js?client-id=AUzKq9qY9xjtvoc_1EXu6fIkYReQCWC5KPWRNG8yjVowdG15ZF0bG0GChEK9zViNFA9IaqQ-ZaoWo3vE&currency=BRL"></script>

<script>
    
    var total = '{{ compras.get_cart_total }}'
    // Render the Paypal button into #paypal-button-container
    paypal.Buttons({

        style: {
            color: 'blue',
            shape: 'rect',
        },

        // Set up the transaction
        createOrder: function (data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: parseFloat(total).toFixed(2)
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function (data, actions) {
            return actions.order.capture().then(function (details) {
                submitFormData()
            });
        }


    }).render('#paypal-button-container');
</script>


<script type="text/javascript">
    var form = document.getElementById('form')

    form.addEventListener('submit', function (e) {
        e.preventDefault()
        console.log('Informe a Forma de Pagamento...')
        document.getElementById('form-button').classList.add('hidden')
        div = document.getElementById('payment-info')
        div.removeAttribute("hidden");
    })
   
    document.getElementById('make-payment').addEventListener('click', function(e){
        submitFormData()
    })
    
    function submitFormData() {
        console.log('Pagamento Efetuado com Sucesso!')

        var shippingInfo = {
            'nome': form.name.value,
            'email': form.email.value,
            'cep': form.cep.value,
            'rua': form.rua.value,
            'bairro': form.bairro.value,
            'cidade': form.cidade.value,
            'estado': form.estado.value,
            'total': total  
        }


        var url = '/process_order/'
        fetch(url,{
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify({'shipping': shippingInfo })
        })
            .then((response) => response.json())
            .then((data) => {
                console.log('Sucess:', data);
                alert('Compra Realizado com Sucesso!');
                window.location.href = "{% url 'consultas' %}"

            })
    }
</script>

{% endblock %}

medline/consulta/templates/cidades.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Cidades{% endblock %}</title>
{% block links %} 
<link rel="stylesheet" type="text/css" href="{% static 'css/cidades.css' %}">

{% endblock %}
{% block main %}
    <h1>Cidades</h1>
    <form method="get">
                <p>Cidade:</p>
                <input type="text">
                <button class="btn btn-primary" type="submit">Filtrar</button>
    </form>
    <div class="row col-md-12">
        <div class="col-lg-12">
            <ul>
            {% for localidade in localidades %}
            {% ifchanged localidade.cidade %}
                <li>{{localidade.cidade}} </li>
            {% endifchanged %}
            {% endfor %}
            </ul>
        </div>
    </div>
{% endblock main %}

medline/consulta/templates/especialidades.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Especialidades{% endblock %}</title>
{% block links %} 
<link rel="stylesheet" type="text/css" href="{% static 'css/especialidades.css' %}">

{% endblock %}

{% block main %}
    <div class="container">
        <h1>Especialidades</h1>
    <form method="get">
                <p>Especialidade:</p>
                {{filtro_especialidade.form.especialidade}}
                <button class="btn btn-primary" type="submit">Filtrar</button>
    </form>
    <div class="row">
        <div class="col-md-12">
            <ul>
            {% for especialidade in especialidades %}
                <li>{{especialidade.especialidade}} </li>
            {% endfor %}
            </ul>
        </div>
    </div>
    </div>
    
{% endblock main %}

medline/consulta/templates/perfil_medico.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Medline - Perfil Medico{% endblock %}</title>
{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'css/content_forms_medico.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/perfil_medico.css' %}">
{% endblock %}
{% block main %}
<div class="container">
	<div class="row m-5">
		<div class="content-forms col-7 mx-auto">
			<h3>Perfil</h3>
			<hr>
			<form method="POST" action="{% url 'perfil_medico' %}" enctype="multipart/form-data">
				{% csrf_token %}
				<div hidden class="input-group mb-3">
					<div class="input-group-prepend">
						<label class="input-group-text" for="inputGroupSelect01">Medico</label>
					</div>
					<select name="id_medico" class="custom-select" required id="id_id_medico">
						<option value="{{request.user.medicos.id}}">{{request.user.medicos}}</option>
					</select>

				</div>

				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<label class="input-group-text" for="inputGroupSelect01">Especialidade</label>
					</div>
					{{ medicos_especialidades.id_especialidade }}

				</div>
				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<span class="input-group-text" id="inputGroup-sizing-default">$</span>
					</div>
					{{ medicos_especialidades.preco }}
					<div class="input-group-prepend">
						<span class="input-group-text" id="inputGroup-sizing-default">Preço</span>

					</div>

				</div>

				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<span class="input-group-text" id="inputGroupFileAddon01">Certificação</span>
					</div>
					<div class="custom-file">
						{{ medicos_especialidades.certificado_especialidade }}
						<label class="custom-file-label" for="inputGroupFile01">Insira o arquivo (Opcional)</label>
					</div>
				</div>

				<div hidden class="input-group mb-3">
					<div class="input-group-prepend">
						<label class="input-group-text" for="inputGroupSelect01">Medico</label>
					</div>
					<select name="user" class="custom-select" required id="id_user">
						<option value="{{request.user.medicos.id}}">{{request.user.medicos}}</option>
					</select>
				</div>

				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<span class="input-group-text" id="inputGroup-sizing-default">CEP</span>
					</div>
					<input type="text" name="cep" class="form-control" maxlength="11" onblur="pesquisacep(this.value);"
						required id="id_cep">
				</div>

				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<span class="input-group-text" id="inputGroup-sizing-default">Rua</span>
					</div>
					{{localidade.rua}}
				</div>

				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<span class="input-group-text" id="inputGroup-sizing-default">Bairro</span>
					</div>
					{{localidade.bairro}}
				</div>

				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<span class="input-group-text" id="inputGroup-sizing-default">Cidade</span>
					</div>
					{{localidade.cidade}}
				</div>

				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<span class="input-group-text" id="inputGroup-sizing-default">Estado</span>
					</div>
					{{localidade.estado}}
				</div>

				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<span class="input-group-text" id="inputGroup-sizing-default">Complemento</span>
					</div>
					{{localidade.complemento}}
				</div>
				<input class="btn login_btn" type="submit" value="Continuar">

			</form>

		</div>
	</div>
</div>
<div class="row images-dt">
	<img src="{% static 'imagens/medical_doctors.png'  %}" class="img-fluid" alt="medicos">
</div>
{% block scripts %}
<script type="text/javascript" src="{% static 'js/cep.js' %}"></script>
{% endblock %}

{% endblock main %}

medline/consulta/templates/user_registration.html
{% extends 'base.html' %}

{% block main %}

<div class="container">
    <form method="POST" action="{% url 'user_registration' %}" id="r_user" class="mx-auto">
        {% include "includes/form_group.html" with form=form %}
        {{ user_registration_form }}

        <div>
            <button class="btn btn-primary btn-block" type="submit">registrar</button>
        </div>
</div>

{% endblock %}